repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args: [--allow-multiple-documents, --unsafe]
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.14
    hooks:
      - id: ruff-check
        args: [--exit-non-zero-on-fix]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        args: [--config-file=./pyproject.toml]
        additional_dependencies:
          - pytest-loco
          - requests
          - requests-toolbelt
          - types-requests
          - yarl
  - repo: local
    hooks:
    - id: pytest
      name: "tests"
      entry: poetry run
      args: ["pytest"]
      language: system
      pass_filenames: false
  - repo: https://github.com/python-poetry/poetry
    rev: 2.3.2
    hooks:
      - id: poetry-check
      - id: poetry-lock
